model:
  base_learning_rate: 1.0e-04
  Domain Name	TTL	Address
A	Gmail.com	300	
142.250.185.101

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

AAAA 
Type	Domain Name	TTL	Address
AAAA	Gmail.com	300	
2a00:1450:4001:80f::2005

Owner: EU Metro Frontend  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

CNAME
Record Not Found
MX 
Type	Domain Name	TTL	Preference	Address
MX	Gmail.com	2381	5	
gmail-smtp-in.l.google.com. (108.177.126.27)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

MX	Gmail.com	2381	30	
alt3.gmail-smtp-in.l.google.com. (142.250.157.27)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By xbl.spamhaus.org | More

MX	Gmail.com	2381	20	
alt2.gmail-smtp-in.l.google.com. (74.125.200.26)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

MX	Gmail.com	2381	40	
alt4.gmail-smtp-in.l.google.com. (173.194.202.26)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

MX	Gmail.com	2381	10	
alt1.gmail-smtp-in.l.google.com. (142.250.150.27)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By sbl.spamhaus.org | More

NS 
Type	Domain Name	TTL	Canonical Name
NS	Gmail.com	21600	
ns2.google.com. (216.239.34.10)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

NS	Gmail.com	21600	
ns4.google.com. (216.239.38.10)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By zen.spamhaus.org | More

NS	Gmail.com	21600	
ns1.google.com. (216.239.32.10)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By sbl.spamhaus.org | More

NS	Gmail.com	21600	
ns3.google.com. (216.239.36.10)

Owner: Google LLC  | WHOIS | AS15169

IP is Blocked By sbl.spamhaus.org | More

PTR
Record Not Found
SRV
Record Not Found
SOA 
Type	Domain Name	TTL	Primary NS	Responsible Email
SOA	Gmail.com	60	ns1.google.com.	dns-admin.google.com.
TXT 
Type	Domain Name	TTL	Record
TXT	Gmail.com	300	v=spf1 redirect=_spf.google.com
TXT	Gmail.com	300	globalsign-smime-dv=CDYX+XFHUw2wml6/Gb8+59BsH31KzUr6c1l2BPvqKX8=
CAA 
Type	Domain Name	TTL	Record
CAA	Gmail.com	21600	0 issue pki.goog
DS
Record Not Found
DNSKEY
Record Not Found
 ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
